// angular-cms/src/app/app.component.ts
import {Component, OnInit, ViewChild, ViewContainerRef} from '@angular/core';
import {rootConfig} from './configurations/root-config';
import {ComponentsFactoryService} from './configurations/components-factory.service';
import {subConfig} from './configurations/sub-config';
//import {subConfig} from './configurations/sub-config';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {


  @ViewChild('root1', { read: ViewContainerRef }) rootComponent1: any;
  @ViewChild('root2', { read: ViewContainerRef }) rootComponent2: any;

  constructor(private cFactory: ComponentsFactoryService) { }

  ngOnInit(): void {
    this.cFactory.build(this.rootComponent1, rootConfig.root);
    this.cFactory.build(this.rootComponent2, subConfig.root);
  }

}

<div>
  <br />
  <br />

  content:

  <table border="1" width="100%" height="300px"><tbody><tr><td>
    Root component 1:
    <template #root1></template>
  </td></tr></tbody></table>

  <br />

  <table border="1" width="100%" height="300px"><tbody><tr><td>
    Root component 2:
    <template #root2></template>
  </td></tr></tbody></table>
</div>

// react-scm/src/App.js
import React, {Component} from 'react';
import logo from './logo.svg';
import './App.css';
import rootConfig from "./configurations/root-config";
import subConfig from "./configurations/sub-config";
import cFactory from "./configurations/components-factory";

class App extends Component {

    render() {

        const rootComponent1 = cFactory.build(rootConfig.root);
        const rootComponent2 = cFactory.build(subConfig.root);

        return (
            <div>
                <br />
                <br />

                content:

                <table border="1" width="100%" height="300px"><tbody><tr><td>
                    Root component 1:
                    {rootComponent1}
                </td></tr></tbody></table>

                <br />

                <table border="1" width="100%" height="300px"><tbody><tr><td>
                    Root component 2:
                    {rootComponent2}
                </td></tr></tbody></table>
            </div>
        );
    }
}

export default App;
